In [1]:
from classifier import riemannianClassifier
from moabb.datasets import BNCI2014001, BNCI2014004, BNCI2015004
from moabb.paradigms import MotorImagery
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import ShuffleSplit
from sklearn.svm import SVC
import warnings

warnings.simplefilter("ignore")

MI = MotorImagery(fmin=8, fmax=32)
datasets = [BNCI2014004(), BNCI2014001(), BNCI2015004()]
dataset_names = ["BNCI2014004", "BNCI2014001", "BNCI2015004"]

X, y, meta = MI.get_data(datasets[1], [1])

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\externals\joblib\__init__.py:15: DeprecationWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=DeprecationWarning)
Choosing from all possible events


In [2]:
n_components = 1
classifiers = {
    "Default": riemannianClassifier(n_components=n_components),
    #"Geodesic Filtering": riemannianClassifier(filtering="geodesic"),
    "TSSF one step": riemannianClassifier(filtering="TSSF", n_components=n_components),
    "TSSF two steps": riemannianClassifier(filtering="TSSF", two_step_classifier=SVC(), n_components=n_components),
}

In [3]:
for clf in classifiers.values():
    clf.fit(X, y)
    #print(list(zip(clf.predict(X), clf.predict_proba(X))))
    
    print(clf)
    print(cross_val_score(clf, X, y, scoring="roc_auc"))

riemannianClassifier(filtering=None, metric='riemann', n_components=None,
                     two_step_classifier=None)
[0.93923611 0.953125   0.94487847]
riemannianClassifier(filtering='TSSF', metric='riemann', n_components=None,
                     two_step_classifier=None)
[0.94791667 0.96701389 0.93880208]
riemannianClassifier(filtering='TSSF', metric='riemann', n_components=None,
                     two_step_classifier=None)
[0.94791667 0.96701389 0.93880208]


In [3]:
svm = SVC()
c2 = riemannianClassifier()

In [5]:
c2.fit(X, y)

riemannianClassifier(filtering='TSSF', metric='riemann', n_components=None,
                     two_step_classifier=None)

In [6]:
import pickle
p = pickle.load(open("params.sav", "rb"))

In [4]:
c2.load_self()

riemannianClassifier(filtering='TSSF', metric='riemann', n_components=None,
                     two_step_classifier=None)

In [10]:
c2.get_params()

{'filtering': 'TSSF',
 'metric': 'riemann',
 'n_components': None,
 'two_step_classifier': None}

In [34]:
from scipy.special import softmax
import numpy as np

In [35]:
softmax([np.abs([9, 8, 0]), np.abs([0, 0, -9])])

array([[4.22252777e-01, 1.55338116e-01, 5.21101325e-05],
       [5.21101325e-05, 5.21101325e-05, 4.22252777e-01]])